/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Metodos.Avisos;
import Metodos.User;
import Metodos.Validador;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emmanuelbarrera
 */
public class Propietario extends javax.swing.JFrame {

    public static Metodos.User propietarioUser;
    public static Metodos.User adminUser;
    ArrayList caracteristicasRegistros = new ArrayList();

    /**
     * Creates new form Propietario
     */
    public Propietario() {
        String[] txtcmbEncontrados = {"Realice una busqueda"};
        initComponents();
        caracteristicasRegistros.addAll(Arrays.asList("ID","Marca", "Modelo", "Placas", "Ano", "Color", "Serie", "Motor", "TarjCirculacion"));
        this.cmbxBusquedaElegida.setModel(new DefaultComboBoxModel(caracteristicasRegistros.toArray()));
        this.cmbEncontrados.setModel(new DefaultComboBoxModel(txtcmbEncontrados));
        this.cmbEncontrados.setEnabled(false);
        this.btnEliminarPropietario.setEnabled(false);
        this.btnModificarPropietario.setEnabled(false);
        if(!adminUser.isAdmin()){
            this.btnAgregarRegistro.setEnabled(false);
            this.btnModificarPropietario.setText("Ver registro");
            this.btnEliminarPropietario.setVisible(false);
        }
        this.actualizarTabla();
        
        if(adminUser.isAdmin()){
            jButton3.setVisible(true);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            txtNombre.setEnabled(true);
            txtApellidos.setEnabled(true);
            txtCorreo.setEnabled(true);
            jButton4.setVisible(true);
            jButton4.setEnabled(false);
        }else{
            jButton3.setVisible(false);
            jButton4.setVisible(false);
        }
        txtNombre.setText(propietarioUser.getNombre());
        txtApellidos.setText(propietarioUser.getApellidos());
        txtCorreo.setText(propietarioUser.getEmail());
        if(propietarioUser.getRFC().equals("No Ingresado")){
            txtRFC.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtRFC.setText(propietarioUser.getRFC());
        if(propietarioUser.getLocalidadCiudad().equals("No Ingresado")){
            txtCiudad.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtCiudad.setText(propietarioUser.getLocalidadCiudad());
        if(propietarioUser.getLocalidadEstado().equals("No Ingresado")){
            txtEstado.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtEstado.setText(propietarioUser.getLocalidadEstado());

        if(propietarioUser.getLocalidadColonia().equals("No Ingresado")){
            txtColonia.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtColonia.setText(propietarioUser.getLocalidadColonia());

        if(propietarioUser.getcodigoPostal()<=0){
            txtCodigoPostal.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtCodigoPostal.setText(""+propietarioUser.getcodigoPostal()+"");

        if(propietarioUser.getDomicilio().equals("No Ingresado")){
            txtDomicilio.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtDomicilio.setText(propietarioUser.getDomicilio());

        if(propietarioUser.getTelefono()<=0){
            txtTel.setEnabled(true);
            jButton1.setText("Guardar cambios");
        }
        txtTel.setText(""+propietarioUser.getTelefono()+"");

        if(jButton1.getText().equals("Guardar cambios")){
            jButton4.setEnabled(true);
            jButton2.setEnabled(true);
        } else {
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnAgregarRegistro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        queryBusqueda = new javax.swing.JTextField();
        cmbxBusquedaElegida = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        cmbEncontrados = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnEliminarPropietario = new javax.swing.JButton();
        btnModificarPropietario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel1.setText("Informacion");

        jLabel2.setText("Nombre");

        txtNombre.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.background"));
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);

        jLabel3.setText("Apellidos");

        txtApellidos.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.background"));
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setEnabled(false);

        jLabel4.setText("Correo:");

        txtCorreo.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.background"));
        txtCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setEnabled(false);

        jLabel5.setText("RFC: ");

        txtRFC.setEnabled(false);
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel6.setText("Localidad");

        jLabel7.setText("Ciudad: ");

        txtCiudad.setEnabled(false);

        jLabel8.setText("Estado: ");

        txtEstado.setEnabled(false);

        jLabel9.setText("Colonia: ");

        txtColonia.setEnabled(false);

        jLabel11.setText("C.P.:");

        txtCodigoPostal.setEnabled(false);

        jLabel12.setText("Domicilio:");

        txtDomicilio.setEnabled(false);

        jLabel13.setText("Tel:");

        txtTel.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel10.setText("Registros");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Propietario");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Contraseña");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nivel Usuario");
        jButton4.setVisible(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnAgregarRegistro.setText("Agregar Registro");
        btnAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegistroActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel15.setText("Modificar Registros");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Buscar registro");

        queryBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                queryBusquedaKeyReleased(evt);
            }
        });

        cmbxBusquedaElegida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cmbEncontrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Registros encontrados");

        btnEliminarPropietario.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        btnEliminarPropietario.setText("Eliminar");
        btnEliminarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPropietarioActionPerformed(evt);
            }
        });

        btnModificarPropietario.setText("Modificar");
        btnModificarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPropietarioActionPerformed(evt);
            }
        });

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161)
                                .addComponent(btnAgregarRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidos)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCorreo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2)
                                                .addGap(0, 0, 0)
                                                .addComponent(jButton4))
                                            .addComponent(txtRFC)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDomicilio))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCiudad))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtColonia)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(103, 103, 103))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbxBusquedaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(queryBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEliminarPropietario)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarPropietario))
                            .addComponent(cmbEncontrados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnAgregarRegistro)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(cmbxBusquedaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarPropietario)
                    .addComponent(btnEliminarPropietario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Avisos avisos = new Avisos();
        String Nombre, Apellidos, Email, RFC, LocalidadCiudad, LocalidadEstado, LocalidadColonia, Domicilio;
        int CodigoPostal=propietarioUser.getcodigoPostal(), Telefono=propietarioUser.getTelefono();

        if( this.jButton1.getText().equals("Modificar")){
            if(adminUser.isAdmin()){
                if(adminUser.confirmacionSeguridad(5)){
                    txtNombre.setEnabled(true);
                    txtApellidos.setEnabled(true);
                    txtCorreo.setEnabled(true);
                    jButton4.setEnabled(true);
                    jButton2.setEnabled(true);
                    txtRFC.setEnabled(true);
                    txtCiudad.setEnabled(true);
                    txtEstado.setEnabled(true);
                    txtColonia.setEnabled(true);
                    txtCodigoPostal.setEnabled(true);
                    txtDomicilio.setEnabled(true);
                    txtTel.setEnabled(true);
                    this.jButton1.setText("Guardar cambios");
                }
            }else if(propietarioUser.confirmacionSeguridad(5)){
                txtRFC.setEnabled(true);
                txtCiudad.setEnabled(true);
                txtEstado.setEnabled(true);
                txtColonia.setEnabled(true);
                txtCodigoPostal.setEnabled(true);
                txtDomicilio.setEnabled(true);
                txtTel.setEnabled(true);
                this.jButton1.setText("Guardar cambios");
            }
        } else if( this.jButton1.getText().equals("Guardar cambios") ) {
            if(avisos.Pregunta("seguro", "continuar")==JOptionPane.YES_OPTION){

                Nombre = txtNombre.getText();
                Apellidos = txtApellidos.getText();
                Email = txtCorreo.getText();
                RFC = txtRFC.getText();
                LocalidadCiudad = txtCiudad.getText();
                LocalidadEstado = txtEstado.getText();
                LocalidadColonia = txtColonia.getText();
                if(!txtCodigoPostal.getText().isEmpty())
                    CodigoPostal = Integer.parseInt(txtCodigoPostal.getText());
                Domicilio = txtDomicilio.getText();
                if(!txtTel.getText().isEmpty())
                    Telefono = Integer.parseInt(txtTel.getText());

                if(!Nombre.equals(propietarioUser.getNombre()) && !Nombre.isEmpty()){
                      propietarioUser.setNombre(Nombre);
                }
                if(!Apellidos.equals(propietarioUser.getApellidos()) && !Apellidos.isEmpty()){
                      propietarioUser.setApellidos(Apellidos);
                }
                if(!Email.equals(propietarioUser.getEmail()) && !Email.isEmpty()){
                      propietarioUser.setEmail(Email);
                }
                if(!RFC.equals(propietarioUser.getRFC()) && !RFC.isEmpty()){
                      propietarioUser.setRFC(RFC);
                }
                if(!LocalidadCiudad.equals(propietarioUser.getLocalidadCiudad()) && !LocalidadCiudad.isEmpty()){
                      propietarioUser.setLocalidadCiudad(LocalidadCiudad);
                }
                if(!LocalidadEstado.equals(propietarioUser.getLocalidadEstado()) && !LocalidadEstado.isEmpty()){
                      propietarioUser.setLocalidadEstado(LocalidadEstado);
                }
                if(!LocalidadColonia.equals(propietarioUser.getLocalidadColonia()) && !LocalidadColonia.isEmpty()){
                      propietarioUser.setLocalidadColonia(LocalidadColonia);
                }
                if(CodigoPostal != propietarioUser.getcodigoPostal()){
                      propietarioUser.setcodigoPostal(CodigoPostal);
                }
                if(!Domicilio.equals(propietarioUser.getDomicilio()) && !Domicilio.isEmpty()){
                      propietarioUser.setDomicilio(Domicilio);
                }
                if(Telefono != propietarioUser.getTelefono()){
                      propietarioUser.setTelefono(Telefono);
                }

                this.jButton1.setText("Modificar");
                jButton4.setEnabled(false);
                jButton2.setEnabled(false);
                txtNombre.setEnabled(false);
                txtApellidos.setEnabled(false);
                txtCorreo.setEnabled(false);
                txtRFC.setEnabled(false);
                txtCiudad.setEnabled(false);
                txtEstado.setEnabled(false);
                txtColonia.setEnabled(false);
                txtCodigoPostal.setEnabled(false);
                txtDomicilio.setEnabled(false);
                txtTel.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(adminUser.isAdmin()){
            if(adminUser.confirmacionSeguridad(5)){
                cambiarContraseña();
            }
        }else if(propietarioUser.confirmacionSeguridad(5)){
                cambiarContraseña();
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void cambiarContraseña(){
        Avisos avisos = new Avisos();
        Validador Validar = new Validador();
        String password;
        String password2;
        password = avisos.Preguntar("password", "nueva");
        password2 = avisos.Preguntar("password", "confirmar");
        if( password2 == null ? false : password2.equals(password) ){
            if (!Validar.longitudString(32, 5, password)){
                avisos = new Avisos("password", "<html><b>Intentelo de nuevo la longitud de su contraseña es incorrecta.<b>\n"
                        + "La contraseña debe contener de 5 caracteres a 32 caracteres");
            } else{
                if(avisos.Pregunta("seguro", "continuar")==JOptionPane.YES_OPTION){
                    propietarioUser.setPassword(propietarioUser.encryptpassword(password));
                }
            }
        }else{
             avisos = new Avisos("password", "noCoinciden");
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(adminUser.confirmacionSeguridad(5)){
            if(propietarioUser.isAdmin()){
                propietarioUser.setUserLevel("user");
            } else {
                propietarioUser.setUserLevel("admin");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void queryBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryBusquedaKeyReleased
        ArrayList<String> listResultados = new ArrayList<String>();
        String[] arrayEncontrados;
        String[] busquedaDefault = {"Realice una busqueda"};
        int row;

        if(!this.queryBusqueda.getText().isEmpty()){
            for(row = 0; row<jTable2.getRowCount(); row++){
                if(this.queryBusqueda.getText().contains(
                    (CharSequence) (""+jTable2.getModel()
                        .getValueAt(row,
                            this.cmbxBusquedaElegida
                            .getSelectedIndex())))){
                listResultados.add(""+jTable2.getModel()
                    .getValueAt(row, 0).toString()
                    + " - " + jTable2.getModel()
                    .getValueAt(row, 1).toString()
                    + ", " + jTable2.getModel()
                    .getValueAt(row, 2).toString()
                    + ", " + jTable2.getModel()
                    .getValueAt(row, 3).toString()
                );
            }
        }
        if(listResultados.isEmpty()){
            listResultados.add("No se han encontrado coincidencias");
            this.cmbEncontrados.setEnabled(false);
            this.btnEliminarPropietario.setEnabled(false);
            this.btnModificarPropietario.setEnabled(false);
        } else {
            this.btnEliminarPropietario.setEnabled(true);
            this.btnModificarPropietario.setEnabled(true);
            this.cmbEncontrados.setEnabled(true);
        }
        arrayEncontrados = (String[]) listResultados.toArray(new String[listResultados.size()]);
        this.cmbEncontrados.setModel(new DefaultComboBoxModel(arrayEncontrados));

        } else {
            this.cmbEncontrados.setModel(new DefaultComboBoxModel(busquedaDefault));
            this.cmbEncontrados.setEnabled(false);
            this.btnEliminarPropietario.setEnabled(false);
            this.btnModificarPropietario.setEnabled(false);
        }
    }//GEN-LAST:event_queryBusquedaKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Metodos.Avisos aviso = new Metodos.Avisos();
        ArrayList<String> listResultados = new ArrayList<String>();
        String[] arrayEncontrados;
        String[] busquedaDefault = {"Realice una busqueda"};
        
        int row;

        if(!this.queryBusqueda.getText().isEmpty()){
            for(row = 0; row<jTable2.getRowCount(); row++){
                if(this.queryBusqueda.getText().contains(
                    (CharSequence) (""+jTable2.getModel()
                        .getValueAt(row,
                            this.cmbxBusquedaElegida
                            .getSelectedIndex())))){
                listResultados.add(""+jTable2.getModel()
                    .getValueAt(row, 0).toString()
                    + " - " + jTable2.getModel()
                    .getValueAt(row, 1).toString()
                    + ", " + jTable2.getModel()
                    .getValueAt(row, 2).toString()
                    + ", " + jTable2.getModel()
                    .getValueAt(row, 3).toString()
                );
            }
        }
        if(listResultados.isEmpty()){
            listResultados.add("No se han encontrado coincidencias");
            this.cmbEncontrados.setEnabled(false);
            this.btnEliminarPropietario.setEnabled(false);
            this.btnModificarPropietario.setEnabled(false);
        } else {
            this.btnEliminarPropietario.setEnabled(true);
            this.btnModificarPropietario.setEnabled(true);
            this.cmbEncontrados.setEnabled(true);
        }
        arrayEncontrados = (String[]) listResultados.toArray(new String[listResultados.size()]);
        this.cmbEncontrados.setModel(new DefaultComboBoxModel(arrayEncontrados));

        } else {
            aviso = new Metodos.Avisos("Busqueda", "ingresaDatos");
            this.cmbEncontrados.setModel(new DefaultComboBoxModel(busquedaDefault));
            this.cmbEncontrados.setEnabled(false);
            this.btnEliminarPropietario.setEnabled(false);
            this.btnModificarPropietario.setEnabled(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnEliminarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPropietarioActionPerformed
        Metodos.Vehiculo vehiculoEliminar = getVehiculocmbEncontrados();
        Metodos.Avisos aviso = new Metodos.Avisos();

        if(aviso.Pregunta("seguro", "continuar")==JOptionPane.YES_OPTION){
            if(adminUser.confirmacionSeguridad(5)){
                this.cmbEncontrados.setEnabled(false);
                this.btnEliminarPropietario.setEnabled(false);
                this.btnModificarPropietario.setEnabled(false);
                if(vehiculoEliminar.deleteVehiculo()){
                    this.cmbEncontrados.setModel(new DefaultComboBoxModel(new String[]{"Realice una busqueda"}));
                    aviso = new Metodos.Avisos("Vehiculo", "eliminado");
                }
                else aviso = new Metodos.Avisos("Vehiculo", "noEliminado");
            }
        }
        actualizarTabla();
    }//GEN-LAST:event_btnEliminarPropietarioActionPerformed

    private void btnModificarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPropietarioActionPerformed
        Metodos.Vehiculo vehiculoModificar = getVehiculocmbEncontrados();
        Metodos.Avisos aviso = new Metodos.Avisos();

        if(vehiculoModificar!=null && vehiculoModificar.existeEnBD){
            this.cmbEncontrados.setEnabled(false);
            this.btnEliminarPropietario.setEnabled(false);
            this.btnModificarPropietario.setEnabled(false);
            Interface.RegistroVehicular.main(vehiculoModificar, adminUser);
        }else{
            aviso = new Metodos.Avisos("Vehiculo","incorrecto");
        }
        actualizarTabla();
    }//GEN-LAST:event_btnModificarPropietarioActionPerformed
    private Metodos.Vehiculo getVehiculocmbEncontrados(){
        String seleccionado = this.cmbEncontrados.getSelectedItem().toString();
        int idVehiculoSeleccionado = Integer.parseUnsignedInt(seleccionado.substring(0,seleccionado.indexOf(" ")));
        return new Metodos.Vehiculo(idVehiculoSeleccionado, propietarioUser.getIdUsuario());
    }
    private void btnAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegistroActionPerformed
        Avisos aviso = new Avisos();
        if(aviso.Pregunta("seguro", "continuar")==JOptionPane.YES_OPTION)
            if(adminUser.isAdmin()) Interface.RegistroVehicular.main(new Metodos.Vehiculo(propietarioUser.getIdUsuario()), adminUser);
            else aviso = new Avisos("userLevel", "incorrecto");
    }//GEN-LAST:event_btnAgregarRegistroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void textTypedToMayusculas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTypedToMayusculas
        this.txtRFC.setText(txtRFC.getText().toUpperCase());
        this.txtCiudad.setText(txtCiudad.getText().toUpperCase());
        this.txtEstado.setText(txtEstado.getText().toUpperCase());
        this.txtColonia.setText(txtColonia.getText().toUpperCase());
        this.txtDomicilio.setText(txtDomicilio.getText().toUpperCase());
    }//GEN-LAST:event_textTypedToMayusculas

    private boolean actualizarTabla(){
        boolean tablaActualizada = true;
        Metodos.Querys query = new Metodos.Querys();
        ResultSet resultSetRegistros;
        String txtQuery="idVehiculo , ";
        int i;
        
        for(i=1; i<(caracteristicasRegistros.size()-1);i++){
            txtQuery+= caracteristicasRegistros.get(i).toString() + " , ";
        }
        txtQuery+= caracteristicasRegistros.get(i).toString();
        
        resultSetRegistros= query.Select(txtQuery
                ,"idUsuario = '"+ propietarioUser.getIdUsuario()+"'"
                , "vehiculos");
        
        DefaultTableModel model = new DefaultTableModel();
        
        for(i=0; i<caracteristicasRegistros.size();i++){
            model.addColumn(caracteristicasRegistros.get(i).toString());
        }
        
        try {
            while (resultSetRegistros.next()){
                int cols = resultSetRegistros.getMetaData().getColumnCount();
                // Se crea un array que será una de las filas de la tabla.
                Object [] fila = new Object[cols]; // Se ingresa el numero total de columnas necesitadas
                // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
                for ( i=0 ; i<cols;i++)
                    fila[i] = resultSetRegistros.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1.
                // Se añade al modelo la fila completa.
                model.addRow(fila);
                tablaActualizada = true;
            }
            this.jTable2.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(PanelControl.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return tablaActualizada;
    }
    /**
     * @param propietarioUserx
     * @param admin
     */
    public static void main(Metodos.User propietarioUser, Metodos.User admin) {
        Propietario.propietarioUser = propietarioUser;
        Propietario.adminUser = admin;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Propietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRegistro;
    private javax.swing.JButton btnEliminarPropietario;
    private javax.swing.JButton btnModificarPropietario;
    private javax.swing.JComboBox<String> cmbEncontrados;
    private javax.swing.JComboBox<String> cmbxBusquedaElegida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField queryBusqueda;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
