/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.Propietario.adminUser;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author emmanuelbarrera
 */
public class RegistroVehicular extends javax.swing.JFrame {

    /**
     * Creates new form RegistrosRecaudadora
     */
    private static Metodos.Vehiculo vehiculoRegistro;
    private static Metodos.User adminUser;

    public RegistroVehicular() {
        initComponents();
        txtTarjCirculacion.setText(0+"");
        cambiarEstadoDeEditables(!vehiculoRegistro.existeEnBD && adminUser.isAdmin());
        //ComboBox
        Calendar micalendar = Calendar.getInstance();
        ArrayList anioslist=new ArrayList();
        int ano=micalendar.get(Calendar.YEAR);
        int anoOpcionales = 100;
        anoOpcionales++;
        for(int i=0; i<=anoOpcionales; i++)
            anioslist.add(String.valueOf(ano-i+1));
        cmbxAno.setModel(new DefaultComboBoxModel(anioslist.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbxAno = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTarjCirculacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Informacion de Vehiculo");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Modelo");

        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel4.setText("Año");

        cmbxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel5.setText("Marca");

        txtPlacas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel6.setText("Placas");

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel7.setText("Color");

        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel8.setText("Serie");

        txtMotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTypedToMayusculas(evt);
            }
        });

        jLabel9.setText("Serie de Motor");

        txtTarjCirculacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isTypedInt(evt);
            }
        });

        jLabel10.setText("Tarjeta de Circulacion");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtModelo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSerie)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 255, Short.MAX_VALUE))
                            .addComponent(txtMotor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(0, 0, 0)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(txtTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Metodos.Avisos avisos = new Metodos.Avisos();
        String Modelo, Marca, Placas, Color, Serie, Motor;
        int Ano = vehiculoRegistro.getAno(), TarjCirculacion = vehiculoRegistro.getTarjCirculacion();

        if( this.btnModificar.getText().equals("Modificar")){
            System.out.print("Entra Guardar");
            if(adminUser.isAdmin()){
                cambiarEstadoDeEditables(adminUser.confirmacionSeguridad(5));
            }else
                JOptionPane.showMessageDialog(null, "Usted no es administrador"
                        , "Problemas de autorizacion", JOptionPane.ERROR_MESSAGE);
        } else if( this.btnModificar.getText().equals("Guardar cambios") ) {
            
            System.out.print("Entra Guardar");
            if(avisos.Pregunta("seguro", "continuar")==JOptionPane.YES_OPTION){

                Modelo = txtModelo.getText();
                Marca = txtMarca.getText();
                Placas = txtPlacas.getText();
                Color = txtColor.getText();
                Serie = txtSerie.getText();
                Motor = txtMotor.getText();
                TarjCirculacion = Integer.parseInt(txtTarjCirculacion.getText());
                Ano = Integer.parseInt((String) cmbxAno.getSelectedItem());

                if(!Modelo.equals(vehiculoRegistro.getModelo()) && !Modelo.isEmpty()){
                    vehiculoRegistro.setModelo(Modelo);
                }
                if(!Marca.equals(vehiculoRegistro.getMarca()) && !Marca.isEmpty()){
                    vehiculoRegistro.setMarca(Marca);
                }
                if(!Placas.equals(vehiculoRegistro.getPlacas()) && !Placas.isEmpty()){
                    vehiculoRegistro.setPlacas(Placas);
                }
                if(!Color.equals(vehiculoRegistro.getColor()) && !Color.isEmpty()){
                    vehiculoRegistro.setColor(Color);
                }
                if(!Serie.equals(vehiculoRegistro.getSerie()) && !Serie.isEmpty()){
                    vehiculoRegistro.setSerie(Serie);
                }
                if(!Motor.equals(vehiculoRegistro.getMotor()) && !Motor.isEmpty()){
                    vehiculoRegistro.setMotor(Motor);
                }
                if(TarjCirculacion !=0 && TarjCirculacion != vehiculoRegistro.getTarjCirculacion()){
                    vehiculoRegistro.setTarjCirculacion(TarjCirculacion);
                }
                if(Ano != vehiculoRegistro.getAno()){
                    vehiculoRegistro.setAno(Ano);
                }
                cambiarEstadoDeEditables(!vehiculoRegistro.checkVehiculo());
            }
        } else
            System.out.print("No Entra a Modifcar ni Guardar");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void textTypedToMayusculas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTypedToMayusculas
        txtModelo.setText(txtModelo.getText().toUpperCase());
        txtMarca.setText(txtMarca.getText().toUpperCase());
        txtPlacas.setText(txtPlacas.getText().toUpperCase());
        txtColor.setText(txtColor.getText().toUpperCase());
        txtSerie.setText(txtSerie.getText().toUpperCase());
        txtMotor.setText(txtMotor.getText().toUpperCase());
    }//GEN-LAST:event_textTypedToMayusculas

    private void isTypedInt(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isTypedInt
        String isNumber = txtTarjCirculacion.getText();
        int number=0;
        if(isNumber.length()<=10){
            try
            {
                number = Integer.parseInt(isNumber);
            } catch (NumberFormatException ex){
                txtTarjCirculacion.setText(isNumber.substring(0, (isNumber.length()-1)));
                new Metodos.Avisos("ingresar solo letras","Este campo solo puede ser llenado con numeros");
            }
        } else
            txtTarjCirculacion.setText(isNumber.substring(0, (isNumber.length()-2)));
    }//GEN-LAST:event_isTypedInt

    private void cambiarEstadoDeEditables(boolean status){
        txtModelo.setEnabled(status);
        cmbxAno.setEnabled(status);
        txtMarca.setEnabled(status);
        txtPlacas.setEnabled(status);
        txtColor.setEnabled(status);
        txtSerie.setEnabled(status);
        txtMotor.setEnabled(status);
        txtTarjCirculacion.setEnabled(status);      
        if(status)this.btnModificar.setText("Guardar cambios");
        else{
            txtModelo.setText(vehiculoRegistro.getModelo());
            cmbxAno.setSelectedItem(""+vehiculoRegistro.getAno());
            txtMarca.setText(vehiculoRegistro.getMarca());
            txtPlacas.setText(vehiculoRegistro.getPlacas());
            txtColor.setText(vehiculoRegistro.getColor());
            txtSerie.setText(vehiculoRegistro.getSerie());
            txtMotor.setText(vehiculoRegistro.getMotor());
            txtTarjCirculacion.setText(vehiculoRegistro.getTarjCirculacion()+"");
            this.btnModificar.setText("Modificar");
        }
    }
    /**
     * @param vehiculoRegistro
     */
    public static void main(Metodos.Vehiculo vehiculoRegistro, Metodos.User adminUser) {
        RegistroVehicular.vehiculoRegistro = vehiculoRegistro;
        RegistroVehicular.adminUser = adminUser;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVehicular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbxAno;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPlacas;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTarjCirculacion;
    // End of variables declaration//GEN-END:variables
}
